name: deploy

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build and Check Package
      uses: hynek/build-and-inspect-python-package@v1.5

    - name: Download Package
      uses: actions/download-artifact@v3
      with:
        name: Packages
        path: dist

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_token }}

    - name: Set up Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: "3.10"
